### PR TITLE
Uncomment authorization_code and meta_data in /oauth/me too

### PR DESCRIPTION
**Pull request by morinel**
- Uncomment authorization_code in admin page, so these work too
- In the /oauth/me I need meta data for the logged in user too, refactored from louisptremblay/wordpress-oauth fork to work with the 3.x version

### CODE REVIEW

**Comment by justingreerbbi** [comment]
3.0.2 Will address the the authorization_code option. Currently, this option has not effect on the actually usages of the OAuth API.

**Comment by morinel** [comment]
Well, actually, it works for me already after I enabled the authorization_code option.

**Comment by justingreerbbi** [comment]
Are you saying that until you enable the auth_code option in wp-admin, that `authorization_code` does not work? This is for version 3.0.1 correct?

**Comment by morinel** [comment]
Yes, correct. I got invalid grant_type "authorization_code" when requesting /oauth/token

**Comment by justingreerbbi** [comment]
Interesting.. All my test show that it was not working correctly so I removed the option until I could figure it out. Well, in that case, I will make a move to release a 3.0.2 with some other options as well within the 3 days grace period.

**Comment by justingreerbbi** [comment]
Version 3.0.2 now has auth code enabled in admin panel. Closing pull request. Please refer to prior comment about extending the /oauth/me method with meta data.

**Pull request closed without merging**
